---
- name: Backup
  hosts: '{{ host }}'
  become: true
  gather_facts: false
  
  #vars:
    #backup_dir: /path_backup_directory
  
  tasks:
    - name: Get current "Date" & "Time"
      ansible.builtin.shell: date +'%c %d-%m-%y'
      register: system_date

    - name: Perform backup
      #ansible.builtin.synchronize:
      copy:
        src: "/etc/httpd/conf/httpd.conf"
        #src: "/etc/"
        #dest: "{{ backup_dir }}/{{ ansible_hostname }}_{{ system_date.stdout }}_/etc/"
        dest: "/tmp/httpd.conf_{{ system_date.stdout }}"
        mode: '0644'
        remote_src: True

